if(NOT DEFINED CCLAW_SOURCE_DIR)
    message(FATAL_ERROR "CCLAW_SOURCE_DIR is required")
endif()

set(profile "${CCLAW_SOURCE_DIR}/profiles/esp32s31-tools.cmake")
if(NOT EXISTS "${profile}")
    message(FATAL_ERROR "Missing esp32s31-tools profile")
endif()

file(READ "${profile}" content)

function(require_profile_line line)
    string(FIND "${content}" "${line}" pos)
    if(pos LESS 0)
        message(FATAL_ERROR "esp32s31-tools profile must contain: ${line}")
    endif()
endfunction()

require_profile_line("set(CC_PROFILE_TARGET_PLATFORM esp32)")
require_profile_line("set(CC_PROFILE_ENABLE_OPENAI ON)")
require_profile_line("set(CC_PROFILE_ENABLE_STREAMING ON)")
require_profile_line("set(CC_PROFILE_ENABLE_FILE_TOOLS ON)")
require_profile_line("set(CC_PROFILE_ENABLE_MEMORY ON)")
require_profile_line("set(CC_PROFILE_ENABLE_ACTIVE_MEMORY ON)")
require_profile_line("set(CC_PROFILE_ENABLE_MULTIMODAL ON)")
require_profile_line("set(CC_PROFILE_ENABLE_MEDIA_IMAGE ON)")
require_profile_line("set(CC_PROFILE_ENABLE_INLINE_BASE64 ON)")
require_profile_line("set(CC_PROFILE_ENABLE_SESSION_STORE_JSON_FILE ON)")
require_profile_line("set(CC_PROFILE_ENABLE_SESSION_STORE_SQLITE OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_SQLITE OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_OLLAMA OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_ANTHROPIC OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_PLUGIN OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_MCP OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_SKILLS OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_MULTI_AGENT OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_RUN_QUEUE OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_TOOL_POOL OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_SHELL OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_DOCKER_SANDBOX OFF)")
require_profile_line("set(CC_PROFILE_ENABLE_ASYNC_OBSERVABILITY OFF)")
